# Generated by Django 6.0.6 on 2026-09-16 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_condicao', models.CharField(choices=[('total_acertos', 'total_acertos'), ('partidas_jogadas', 'partidas_jogadas'), ('streak_dias', 'streak_dias'), ('acertos_por_banca', 'acertos_por_banca'), ('acertos_por_materia', 'acertos_por_materia')], help_text='Tipo de condição avaliada — lista vem do catálogo fixo em conquistas/services.py', max_length=50)),
                ('parametros', models.JSONField(blank=True, default=dict, help_text='Ex.: {"meta": 500} ou {"banca_id": 3, "meta": 500}. A chave "meta" é sempre obrigatória.')),
                ('recompensa_xp', models.PositiveIntegerField(default=0)),
                ('recompensa_moedas', models.PositiveIntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, help_text='Imagem própria da conquista (estilo Steam) — colorida quando desbloqueada.', null=True, upload_to='conquistas/')),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Controla a ordem de exibição no perfil')),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ConquistaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso', models.PositiveIntegerField(default=0)),
                ('completada', models.BooleanField(default=False)),
                ('completada_em', models.DateTimeField(blank=True, null=True)),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='conquistas.conquista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conquista do Usuário',
                'verbose_name_plural': 'Conquistas dos Usuários',
                'ordering': ['-completada_em', 'conquista__ordem'],
                'unique_together': {('usuario', 'conquista')},
            },
        ),
    ]
