# Generated by Django 6.0.6 on 2026-09-16 07:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conquistas', '0001_initial'),
        ('questoes', '0003_respostausuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conquista',
            options={'ordering': ['nome'], 'verbose_name': 'Conquista', 'verbose_name_plural': 'Conquistas'},
        ),
        migrations.AlterModelOptions(
            name='conquistausuario',
            options={'ordering': ['-completada_em', 'conquista__nome'], 'verbose_name': 'Conquista do Usuário', 'verbose_name_plural': 'Conquistas dos Usuários'},
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='parametros',
        ),
        migrations.AddField(
            model_name='conquista',
            name='banca',
            field=models.ForeignKey(blank=True, help_text='Só usado quando tipo_condicao = acertos_por_banca.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conquistas', to='questoes.banca'),
        ),
        migrations.AddField(
            model_name='conquista',
            name='materia',
            field=models.ForeignKey(blank=True, help_text='Só usado quando tipo_condicao = acertos_por_materia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conquistas', to='questoes.materia'),
        ),
        migrations.AddField(
            model_name='conquista',
            name='meta',
            field=models.PositiveIntegerField(default=1, help_text='Valor que o usuário precisa atingir pra completar a conquista.', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
