# Generated by Django 6.0.6 on 2026-09-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conquistas', '0002_alter_conquista_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conquistausuario',
            name='valor_inicial',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
