# Generated by Django 6.0.6 on 2026-09-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conquistas', '0003_conquistausuario_valor_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conquista',
            name='imagem_pb',
            field=models.ImageField(blank=True, editable=False, help_text='Gerada automaticamente a partir de "imagem" (ver conquistas/signals.py) — versão preto-e-branco usada quando a conquista está bloqueada. Não editar na mão.', null=True, upload_to='conquistas/pb/'),
        ),
        migrations.AlterField(
            model_name='conquista',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem própria da conquista (estilo Steam) — colorida, mostrada quando desbloqueada.', null=True, upload_to='conquistas/'),
        ),
    ]
