# Generated by Django 6.0.6 on 2026-06-24 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Banca',
                'verbose_name_plural': 'Bancas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Matéria',
                'verbose_name_plural': 'Matérias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=200)),
                ('ano', models.IntegerField()),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concursos', to='questoes.banca')),
            ],
            options={
                'verbose_name': 'Concurso',
                'verbose_name_plural': 'Concursos',
                'ordering': ['-ano', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(choices=[('multipla_escolha', 'Múltipla Escolha'), ('certo_errado', 'Certo/Errado'), ('discursiva', 'Discursiva')], max_length=20)),
                ('enunciado', models.TextField()),
                ('contexto', models.TextField(blank=True, help_text='Texto-base compartilhado por múltiplas questões')),
                ('gabarito', models.CharField(blank=True, max_length=1)),
                ('tem_imagem', models.BooleanField(default=False, help_text='Script detectou referência a imagem/figura')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='questoes/imagens/')),
                ('baixa_confianca', models.BooleanField(default=False, help_text='Extração com possíveis problemas')),
                ('notas_extracao', models.JSONField(blank=True, default=list, help_text='Alertas gerados pelo script')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10)),
                ('pagina_pdf', models.IntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='questoes.concurso')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='questoes.materia')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['concurso', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=1)),
                ('texto', models.TextField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='questoes.questao')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
                'ordering': ['letra'],
            },
        ),
    ]
