# Generated by Django 6.0.6 on 2026-07-02 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questoes_ids', models.JSONField(default=list)),
                ('respondidas_ids', models.JSONField(default=list)),
                ('acertos', models.PositiveIntegerField(default=0)),
                ('erros', models.PositiveIntegerField(default=0)),
                ('com_tempo', models.BooleanField(default=False)),
                ('finalizada', models.BooleanField(default=False)),
                ('abandonada', models.BooleanField(default=False)),
                ('xp_ganho', models.PositiveIntegerField(default=0)),
                ('moedas_ganhas', models.PositiveIntegerField(default=0)),
                ('vidas_perdidas', models.PositiveIntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
