# Generated by Django 6.0.6 on 2026-10-07 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0003_respostausuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='concurso',
            name='nivel',
            field=models.CharField(blank=True, choices=[('fundamental', 'Ensino fundamental'), ('medio', 'Ensino médio'), ('superior', 'Ensino superior')], max_length=12),
        ),
        migrations.AddField(
            model_name='materia',
            name='aliases',
            field=models.TextField(blank=True, help_text='Outros nomes desta matéria nas provas, um por linha (ex.: "Noções de Direito Penal"). O importador usa isso para unificar sozinho.'),
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome curto, exibido no app (ex.: TJRJ)', max_length=150, unique=True)),
                ('nome_completo', models.CharField(blank=True, max_length=250)),
                ('esfera', models.CharField(choices=[('federal', 'Nacional (federal)'), ('estadual', 'Estadual'), ('municipal', 'Municipal')], max_length=10)),
                ('uf', models.CharField(blank=True, choices=[('AC', 'AC — Acre'), ('AL', 'AL — Alagoas'), ('AM', 'AM — Amazonas'), ('AP', 'AP — Amapá'), ('BA', 'BA — Bahia'), ('CE', 'CE — Ceará'), ('DF', 'DF — Distrito Federal'), ('ES', 'ES — Espírito Santo'), ('GO', 'GO — Goiás'), ('MA', 'MA — Maranhão'), ('MG', 'MG — Minas Gerais'), ('MS', 'MS — Mato Grosso do Sul'), ('MT', 'MT — Mato Grosso'), ('PA', 'PA — Pará'), ('PB', 'PB — Paraíba'), ('PE', 'PE — Pernambuco'), ('PI', 'PI — Piauí'), ('PR', 'PR — Paraná'), ('RJ', 'RJ — Rio de Janeiro'), ('RN', 'RN — Rio Grande do Norte'), ('RO', 'RO — Rondônia'), ('RR', 'RR — Roraima'), ('RS', 'RS — Rio Grande do Sul'), ('SC', 'SC — Santa Catarina'), ('SE', 'SE — Sergipe'), ('SP', 'SP — São Paulo'), ('TO', 'TO — Tocantins')], help_text='Obrigatório para órgãos estaduais e municipais', max_length=2)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orgaos', to='questoes.categoria')),
            ],
            options={
                'verbose_name': 'Órgão',
                'verbose_name_plural': 'Órgãos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='concurso',
            name='orgao',
            field=models.ForeignKey(blank=True, help_text='Concursos antigos podem ficar sem órgão, mas só aparecem nos filtros por categoria/esfera/estado depois de ligados a um.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concursos', to='questoes.orgao'),
        ),
    ]
