# Generated by Django 6.0.6 on 2026-07-07 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questoes', '0002_partida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLojaVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('pula_questao', 'Pula Questão'), ('elimina_alternativas', 'Elimina 2 Alternativas'), ('xp_dobro', 'XP em Dobro por 24h'), ('congela_streak', 'Congelamento de Streak'), ('vida_extra', 'Vida Extra')], max_length=30, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco_moedas', models.PositiveIntegerField()),
                ('tipo_efeito', models.CharField(choices=[('consumivel_partida', 'Consumível dentro da partida'), ('temporario', 'Ativo por tempo limitado'), ('protecao_streak', 'Protege o streak'), ('credito_direto', 'Credita direto no saldo do usuário')], max_length=30)),
                ('quantidade_concedida', models.PositiveIntegerField(default=1, help_text='Ex: 1 vida extra, ou N usos do buff')),
                ('duracao_horas', models.PositiveIntegerField(blank=True, help_text="Só usado por itens 'temporario', ex: xp_dobro = 24", null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Deve ser idêntico ao Product ID no Play Console / App Store Connect', max_length=100, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('moedas', 'Pacote de Moedas'), ('vida_avulsa', 'Vida Avulsa')], max_length=20)),
                ('quantidade', models.PositiveIntegerField(help_text='Quantas moedas ou vidas esse SKU entrega')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuffAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buffs_ativos', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.itemlojavirtual')),
            ],
        ),
        migrations.CreateModel(
            name='CompraLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_token', models.CharField(help_text='Token do Google/Apple — impede crédito duplicado da mesma compra', max_length=500, unique=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('validada', 'Validada'), ('rejeitada', 'Rejeitada'), ('reembolsada', 'Reembolsada')], default='pendente', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('validada_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='loja.produtoloja')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioBuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_buffs', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.itemlojavirtual')),
            ],
            options={
                'unique_together': {('usuario', 'item')},
            },
        ),
        migrations.CreateModel(
            name='UsoBuffPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usado_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.itemlojavirtual')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_buff', to='questoes.partida')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('partida', 'questao', 'item')},
            },
        ),
    ]
