# Generated by Django 6.0.6 on 2026-09-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
        ('questoes', '0002_partida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        # ─────────────────────────────────────────────
        # 1. Renomeia o catálogo de itens primeiro.
        # Isso precisa acontecer antes de qualquer FK
        # que aponte para loja.ItemLoja.
        # ─────────────────────────────────────────────
        migrations.RenameModel(
            old_name='ItemLojaVirtual',
            new_name='ItemLoja',
        ),

        # ─────────────────────────────────────────────
        # 2. ProdutoLoja -> ProdutoIAP
        # ─────────────────────────────────────────────
        migrations.RenameModel(
            old_name='ProdutoLoja',
            new_name='ProdutoIAP',
        ),

        migrations.AlterField(
            model_name='produtoiap',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('moedas', 'Pacote de Moedas'),
                ],
                max_length=20,
            ),
        ),

        migrations.AlterField(
            model_name='produtoiap',
            name='quantidade',
            field=models.PositiveIntegerField(
                help_text='Quantas moedas esse SKU entrega'
            ),
        ),

        # ─────────────────────────────────────────────
        # 3. CompraLoja -> CompraIAP
        # Agora o ProdutoIAP já existe no estado da migration.
        # ─────────────────────────────────────────────
        migrations.RenameModel(
            old_name='CompraLoja',
            new_name='CompraIAP',
        ),

        migrations.AlterField(
            model_name='compraiap',
            name='produto',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='compras',
                to='loja.produtoiap',
            ),
        ),

        # ─────────────────────────────────────────────
        # 4. InventarioBuff -> InventarioItem
        # ─────────────────────────────────────────────
        migrations.RenameModel(
            old_name='InventarioBuff',
            new_name='InventarioItem',
        ),

        migrations.AlterField(
            model_name='inventarioitem',
            name='usuario',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='inventario_itens',
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        # ─────────────────────────────────────────────
        # 5. UsoBuffPartida -> UsoItemPartida
        # ─────────────────────────────────────────────
        migrations.RenameModel(
            old_name='UsoBuffPartida',
            new_name='UsoItemPartida',
        ),

        migrations.AlterField(
            model_name='usoitempartida',
            name='partida',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='usos_item',
                to='questoes.partida',
            ),
        ),

        # ─────────────────────────────────────────────
        # 6. Campos do usuário no UsoItemPartida
        # ─────────────────────────────────────────────
        migrations.AlterField(
            model_name='usoitempartida',
            name='usuario',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        # ─────────────────────────────────────────────
        # 7. Garantir a constraint atual
        # ─────────────────────────────────────────────
        migrations.AlterUniqueTogether(
            name='inventarioitem',
            unique_together={('usuario', 'item')},
        ),

        migrations.AlterUniqueTogether(
            name='usoitempartida',
            unique_together={('partida', 'questao', 'item')},
        ),
    ]