# Generated by Django 6.0.6 on 2026-09-26 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_inventarioitem_produtoiap_usoitempartida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.itemloja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de compra de item',
                'verbose_name_plural': 'Histórico de compras de itens',
                'ordering': ['-criado_em'],
            },
        ),
    ]
