# Generated by Django 6.0.6 on 2026-06-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_ultima_partida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='moedas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vidas',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vidas_atualizadas_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
