# Generated by Django 6.0.6 on 2026-07-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_data_ultima_partida_usuario_moedas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_recuperacao_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_recuperacao_senha',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
