# Generated by Django 6.0.6 on 2026-07-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_codigo_recuperacao_expira_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='vidas',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
