# Generated by Django 6.0.6 on 2026-09-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_vidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_verificacao_email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
