# Generated by Django 6.0.6 on 2026-09-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_token_verificacao_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_pendente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
