# Generated by Django 6.0.6 on 2026-09-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_email_pendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_exclusao_conta',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_exclusao_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
