# Generated by Django 6.0.6 on 2026-09-24 22:39

import django.db.models.deletion
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_token_exclusao_conta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioVidaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=usuarios.models._gerar_token_anuncio, max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('confirmado_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_vida_extra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anúncio de vida extra',
                'verbose_name_plural': 'Anúncios de vida extra',
                'ordering': ['-criado_em'],
            },
        ),
    ]
