# Generated by Django 6.0.6 on 2026-09-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_anunciovidaextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notificacoes_ativadas',
            field=models.BooleanField(default=True),
        ),
    ]
