# Generated by Django 6.0.6 on 2026-09-27 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_expo_push_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vidas_restauradas', 'Vidas restauradas'), ('streak_em_risco', 'Streak em risco'), ('convite_casual', 'Convite casual'), ('desafio_60s', 'Desafio de 60 segundos'), ('reengajamento', 'Reengajamento')], max_length=20)),
                ('data', models.DateField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação enviada',
                'verbose_name_plural': 'Notificações enviadas',
                'ordering': ['-enviado_em'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'tipo', 'data'), name='notificacao_unica_por_usuario_tipo_dia')],
            },
        ),
    ]
