# Generated by Django 6.0.6 on 2026-10-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_notificacaoenviada'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='vidas_extras',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
