# Generated by Django 6.0.6 on 2026-09-26 06:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja', '0003_historicocompraitem'),
        ('questoes', '0003_respostausuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(help_text='Texto curto mostrado na listagem, ex.: "Jogue 1 partida hoje".', max_length=150)),
                ('tipo_condicao', models.CharField(choices=[('partidas_jogadas_hoje', 'partidas_jogadas_hoje'), ('total_acertos_hoje', 'total_acertos_hoje'), ('total_erros_hoje', 'total_erros_hoje'), ('acertos_por_banca_hoje', 'acertos_por_banca_hoje'), ('acertos_por_materia_hoje', 'acertos_por_materia_hoje'), ('usar_item_hoje', 'usar_item_hoje'), ('comprar_item_hoje', 'comprar_item_hoje'), ('partida_em_horario_hoje', 'partida_em_horario_hoje')], help_text='Tipo de condição avaliada — lista vem do catálogo fixo em desafios/services.py', max_length=50)),
                ('meta', models.PositiveIntegerField(help_text='Valor que o usuário precisa atingir HOJE pra completar o desafio.', validators=[django.core.validators.MinValueValidator(1)])),
                ('horario_inicio', models.TimeField(blank=True, help_text='Só usado quando tipo_condicao = partida_em_horario_hoje. Ex.: 05:00.', null=True)),
                ('horario_fim', models.TimeField(blank=True, help_text='Só usado quando tipo_condicao = partida_em_horario_hoje. Ex.: 10:00.', null=True)),
                ('recompensa_xp', models.PositiveIntegerField(default=0)),
                ('recompensa_moedas', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('banca', models.ForeignKey(blank=True, help_text='Só usado quando tipo_condicao = acertos_por_banca_hoje.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desafios', to='questoes.banca')),
                ('item', models.ForeignKey(blank=True, help_text='Usado por usar_item_hoje (obrigatório) e comprar_item_hoje (opcional — vazio conta compra de qualquer item da loja).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desafios', to='loja.itemloja')),
                ('materia', models.ForeignKey(blank=True, help_text='Só usado quando tipo_condicao = acertos_por_materia_hoje.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desafios', to='questoes.materia')),
            ],
            options={
                'verbose_name': 'Desafio',
                'verbose_name_plural': 'Desafios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DesafioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('progresso', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('completado_em', models.DateTimeField(blank=True, null=True)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='desafios.desafio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desafio do Usuário',
                'verbose_name_plural': 'Desafios dos Usuários',
                'ordering': ['desafio__nome'],
                'unique_together': {('usuario', 'desafio', 'data')},
            },
        ),
    ]
